[package]
name = "hartexbuild-hartexfile"
version = "0.1.0"
edition = "2021"
description = """
Hartexfile specification for HarTex buildsystem
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }

hcl-rs = "0.12.3"

[features]
