[package]
name = "hartex_database_migrate"
version = "0.10.0"
edition = "2021"
description = """
Database migrations.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.80.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_log = { path = "../../rust-utilities/hartex-log" }

dotenvy = "0.15.7"
miette = { version = "7.2.0", features = ["fancy"] }
tokio = "1.37.0"
