[package]
name = "hartex_discord_entitycache_test"
version = "0.7.1"
edition = "2021"
description = """
Test suite for the command framework (macros).
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }

[dev-dependencies]
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core", features = ["derive"] }
hartex_discord_entitycache_macros = { path = "../hartex-discord-entitycache-macros" }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }

macrotest = { git = "https://github.com/TeamHarTex/macrotest.git", branch = "master" }
rustversion = "1.0.14"
tokio-postgres = "0.7.10"
trybuild = "1.0.88"
twilight-model = { git = "https://github.com/TeamHarTex/twilight.git", branch = "next" }
