[workspace]
members = [
    "hartex-discord-utils",
    "hartex-errors",
    "hartex-kafka-utils",
    "hartex-log",
    "hartex-macro-utils",
]

resolver = "2"

[profile.release]
debug = true
lto = true
