[package]
name = "hartex_discord_utils"
version = "0.5.1"
edition = "2021"
description = """
Macro utilities
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../../discord-frontend/hartex-discord-core", features = ["discord-http", "discord-model"] }

hartex_localization_core = { path = "../../localization/hartex-localization-core" }

miette = "5.10.0"
once_cell = "1.18.0"
unic-langid = "0.9.2"

[features]
