[package]
name = "hartex_discord_configuration_luart"
version = "0.8.0"
edition = "2021"
description = """
The worker component of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.78.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.9.6", features = ["lua54", "vendored"] }

[dev-dependencies]
expect-test = "1.4.1"

[features]
