[package]
name = "hartex_localization_core"
version = "0.1.0"
edition = "2021"
description = """
Localization infrastructure for HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.70.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }

fluent-bundle = { git = "https://github.com/TeamHarTex/fluent-rs.git", branch = "main" }
intl-memoizer = { git = "https://github.com/TeamHarTex/fluent-rs.git", branch = "main" }
unic-langid = { version = "0.9.1", features = ["macros"] }

[features]
