[package]
name = "hartex_localization_core"
version = "0.8.0"
edition = "2021"
description = """
Localization infrastructure for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_localization_bindings = { path = "../hartex-localization-bindings" }
hartex_localization_loader = { path = "../../localization/hartex-localization-loader" }

fluent-bundle = "0.15.2"
fluent-syntax = "0.11.0"
intl-memoizer = "0.5.1"
lazy_static = "1.4.0"
miette = "6.0.1"
unic-langid = { version = "0.9.4", features = ["macros"] }

[features]
