[package]
name = "hartex_errors"
version = "0.12.0"
edition = "2021"
description = """
Errors in HarTex. All are displayed in the console but some may appear on Discord.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.82.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "7.2.0"
thiserror = "1.0.61"

[features]
