[package]
name = "hartex_errors"
version = "0.8.0"
edition = "2021"
description = """
Errors in HarTex. All are displayed in the console but some may appear on Discord.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.78.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "6.0.1"
thiserror = "1.0.56"

[features]
