[package]
name = "hartex_discord_configuration_test"
version = "0.5.1"
edition = "2021"
description = """
Test suite for the configuration API.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_configuration_manifest = { path = "../hartex-discord-configuration-manifest" }

[dev-dependencies]
pretty_assertions = "1.4.0"
