[package]
name = "hartexbuild_driver"
version = "0.6.0"
edition = "2021"
description = """
HarTex buildsystem binary
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartexbuild_hartexfile = { path = "../hartexbuild-hartexfile" }

hartex_errors = { path = "../../rust-utilities/hartex-errors" }

clap = "4.4.11"
miette = { version = "5.10.0", features = ["fancy"] }

[features]

[[bin]]
name = "hartexbuild"
path = "src/main.rs"
