[package]
name = "uitest"
version = "0.7.1"
edition = "2021"
description = """
UI test binary
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

[dependencies]


[[bin]]
name = "uitest"
path = "src/bin/main.rs"
