[package]
name = "hartex_discord_worker"
version = "0.1.0"
edition = "2021"
description = """
The worker component of the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_commands = { path = "../hartex-discord-commands" }
hartex_discord_commands_core = { path = "../hartex-discord-commands-core" }
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-runtime", "async-signal", "discord-model", "environment", "logging-facilities"] }
hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }
hartex_discord_entitycache_cacheupdaters = { path = "../hartex-discord-entitycache-cacheupdaters" }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }
hartex_kafka_utils = { path = "../../rust-utilities/hartex-kafka-utils" }

futures-util = "0.3.27"
once_cell = "1.17.1"
rdkafka = { version = "0.29.0", default-features = false, features = ["cmake-build", "external-lz4", "tokio"] }
serde = "1.0.154"
serde_json = "1.0.94"
serde_scan = "0.4.1"
tracing = { version = "0.1.37", features = ["log-always" ] }

[features]
