[package]
name = "hartexbuild_hartexfile"
version = "0.1.0"
edition = "2021"
description = """
HarTexfile specification for HarTex buildsystem
"""
license = "AGPL-3.0-only"
rust-version = "1.72.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }

serde = { version = "1.0.169", features = ["derive"] }
hcl-rs = "0.15.0"

[features]
