[package]
name = "hartex_discord_configuration_provider"
version = "0.12.0"
edition = "2021"
description = """
The worker component of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }

[features]
