[package]
name = "hartex_discord_commands_manager"
version = "0.7.1"
edition = "2021"
description = """
The commands manager of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-net", "async-runtime", "discord-model", "environment"] }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

clap = "4.4.18"
hyper = { version = "1.1.0", features = ["client", "http1"] }
hyper-trust-dns = { version = "0.5.0", features = ["native-tls"] }
hyper-util = { version = "0.1.3", features = ["http1", "tokio"] }
http-body-util = "0.1.0"
miette = { version = "5.10.0", features = ["fancy"] }
minify = "1.3.0"
owo-colors = "4.0.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
walkdir = "2.4.0"

[features]
