[workspace]
members = [
    "hartex-bors-commands",
    "hartex-bors-core",
    "hartex-bors-database",
    "hartex-bors-dashboard",
    "hartex-bors-driver",
    "hartex-bors-github",
    "hartex-bors-permissions",
]

resolver = "2"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
