[workspace]
members = [
    "hartex-bors-commands",
    "hartex-bors-core",
    "hartex-bors-database",
    "hartex-bors-driver",
    "hartex-bors-github",
    "hartex-bors-permissions",
]

resolver = "2"
