[package]
name = "hartexbuild_main"
version = "0.1.0"
edition = "2021"
description = """
HarTex buildsystem binary
"""
license = "AGPL-3.0-only"
rust-version = "1.70.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartexbuild_hartexfile = { path = "../hartexbuild-hartexfile" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }

clap = "4.2.1"

[features]

[[bin]]
name = "hartexbuild"
path = "src/main.rs"
