[package]
name = "hartex_discord_entitycache_macros"
version = "0.4.0"
edition = "2021"
description = """
Macros for the command framework.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
lazy_static = "1.4.0"
proc-macro2 = "1.0.67"
quote = "1.0.33"
syn = { version = "2.0.37", features = ["extra-traits", "full"] }

[build-dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.67"
quote = "1.0.33"
reqwest = { version = "0.11.20", features = ["blocking"] }
syn = { version = "2.0.37", features = ["extra-traits", "full"] }
zip = { version = "0.6.6" }

[features]
default = ["discord_model_v_0_15_4"]
discord_model_v_0_15_4 = []

[lib]
name = "hartex_discord_entitycache_macros"
proc-macro = true
