[package]
name = "hartex_discord_entitycache_macros"
version = "0.9.0"
edition = "2021"
description = """
Macros for the command framework.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.79.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.6.0"
itertools = "0.12.1"
lazy_static = "1.4.0"
pluralizer = "0.4.0"
proc-macro2 = "1.0.80"
quote = "1.0.36"
syn = { version = "2.0.59", features = ["extra-traits", "full"] }
hartex-macro-utils = { version = "0.1.0", path = "../../rust-utilities/hartex-macro-utils" }

[build-dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.80"
quote = "1.0.36"
reqwest = { version = "0.12.3", features = ["blocking"] }
syn = { version = "2.0.59", features = ["extra-traits", "full"] }
zip = { version = "0.6.6" }

[features]
default = ["discord_model_v_0_15_4"]
discord_model_v_0_15_4 = []
discord_model_git = []

[lib]
name = "hartex_discord_entitycache_macros"
proc-macro = true
