[package]
name = "hartex_discord_entitycache_macros"
version = "0.1.0"
edition = "2021"
description = """
Macros for the command framework.
"""
license = "AGPL-3.0-only"
rust-version = "1.72.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.59"
quote = "1.0.28"
syn = { version = "2.0.18", features = ["extra-traits", "full"] }

[features]

[lib]
name = "hartex_discord_entitycache_macros"
proc-macro = true
