[package]
name = "hartex_discord_leader"
version = "0.7.1"
edition = "2021"
description = """
The leader component of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-runtime", "async-signal", "discord-model", "discord-gateway", "environment"] }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }
hartex_kafka_utils = { path = "../../rust-utilities/hartex-kafka-utils" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

futures-util = "0.3.30"
miette = { version = "5.10.0", features = ["fancy"] }
rdkafka = { version = "0.36.1", default-features = false, features = ["cmake-build", "external-lz4", "tokio"] }
serde_json = "1.0.111"
serde_scan = "0.4.1"
once_cell = "1.19.0"
tracing = { version = "0.1.40", features = ["log-always"] }

[features]
