[package]
name = "hartex_discord_leader"
version = "0.1.0"
edition = "2021"
description = """
The leader component of the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-runtime", "async-signal", "discord-model", "discord-gateway", "environment"] }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_kafka_utils = { path = "../../rust-utilities/hartex-kafka-utils" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

futures-util = "0.3.28"
rdkafka = { version = "0.33.2", default-features = false, features = ["cmake-build", "external-lz4", "tokio"] }
tracing = { version = "0.1.37", features = ["log-always" ]}

[features]
