[workspace]
members = [
    "hartex-localization-bindings",
    "hartex-localization-core",
    "hartex-localization-loader",
    "hartex-localization-macros",
    "hartex-localization-test",
]

resolver = "2"

[profile.release]
debug = true
lto = true
