[package]
name = "hartex_backend_routes_v1"
version = "0.1.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master", features = ["json"] }
serde = "1.0.156"

[features]
