[package]
name = "hartex_bors_database"
version = "0.5.1"
edition = "2021"
description = """
HarTex bors database driver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_core = { path = "../hartex-bors-core" }

chrono = { version = "0.4.31", features = ["clock"], default-features = false }
miette = "5.10.0"
octocrab = "0.32.0"
sea-orm = { version = "0.12.8", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
sea-orm-migration = { version = "0.12.6", features = ["runtime-tokio-native-tls", "sqlx-sqlite"] }
serde = { version = "1.0.193", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio-native-tls", "sqlite"] }

[features]
