[package]
name = "hartex_bors_database"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors database driver
"""
license = "AGPL-3.0-only"
rust-version = "1.71.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_core = { path = "../hartex-bors-core" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }

[features]
