[package]
name = "hartex_kafka_utils"
version = "0.1.0"
edition = "2021"
description = """
Macro utilities
"""
license = "AGPL-3.0-only"
rust-version = "1.72.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { version = "0.32.2", default-features = false, features = ["cmake-build", "external-lz4", "tokio"] }

[features]
