[workspace]
members = [
    "hartex-backend-driver",
    "hartex-backend-models",
    "hartex-backend-models-v2",
    "hartex-backend-ratelimiter",
    "hartex-backend-routes-v2",
    "hartex-backend-status-util",
]

resolver = "2"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
