[workspace]
members = [
    "hartex-backend-driver",
    "hartex-backend-models",
    "hartex-backend-models-v1",
    "hartex-backend-ratelimiter",
    "hartex-backend-routes-v1",
    "hartex-backend-status-util",
]

resolver = "2"

[profile.release]
debug = true
lto = true
