[package]
name = "hartex_localization_loader"
version = "0.12.0"
edition = "2021"
description = """
Localization loader for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent-bundle = "0.15.3"
fluent-syntax = "0.11.1"
intl-memoizer = "0.5.2"
miette = "7.2.0"
unic-langid = { version = "0.9.5", features = ["macros"] }
walkdir = "2.5.0"

[features]
