[package]
name = "hartex_localization_loader"
version = "0.5.1"
edition = "2021"
description = """
Localization loader for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent-bundle = "0.15.2"
fluent-syntax = "0.11.0"
intl-memoizer = "0.5.1"
miette = "5.10.0"
unic-langid = { version = "0.9.1", features = ["macros"] }

[features]
