[package]
name = "hartex_bors_driver"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors binary
"""
license = "AGPL-3.0-only"
rust-version = "1.71.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_commands = { path = "../hartex-bors-commands" }
hartex_bors_core = { path = "../hartex-bors-core" }
hartex_bors_database = { path = "../hartex-bors-database" }
hartex_bors_github = { path = "../hartex-bors-github" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

dotenvy = "0.15.7"
futures-util = "0.3.28"
octocrab = { git = "https://github.com/TeamHarTex/octocrab.git" }
reqwest-eventsource = { git = "https://github.com/TeamHarTex/reqwest-eventsource.git" }
sea-orm = { version = "0.12.0-rc.2", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
sea-orm-migration = { version = "0.12.0-rc.2", features = ["sqlx-sqlite", "runtime-tokio-native-tls"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "sync"] }

[features]

[[bin]]
name = "bors"
path = "src/main.rs"
