[package]
name = "hartex_bors_driver"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors binary
"""
license = "AGPL-3.0-only"
rust-version = "1.70.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]

[[bin]]
name = "bors"
path = "src/main.rs"
