[package]
name = "hartex_bors_driver"
version = "0.3.0"
edition = "2021"
description = """
HarTex bors binary
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_commands = { path = "../hartex-bors-commands" }
hartex_bors_core = { path = "../hartex-bors-core" }
hartex_bors_database = { path = "../hartex-bors-database" }
hartex_bors_github = { path = "../hartex-bors-github" }

hartex_errors = { path = "../../rust-utilities/hartex-errors" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

dotenvy = "0.15.7"
futures-util = "0.3.28"
miette = { version = "5.10.0", features = ["fancy"] }
octocrab = { git = "https://github.com/TeamHarTex/octocrab.git" }
reqwest-eventsource = { git = "https://github.com/TeamHarTex/reqwest-eventsource.git" }
serde_json = "1.0.104"
state = "0.6.0"
tokio = { version = "1.30.0", features = ["rt-multi-thread", "sync"] }

[features]
