[book]
authors = ["HTGAzureX1212"]
language = "en"
multilingual = false
src = "src"
title = "HarTex Contributors' Documentation"

[build]
build-dir = "../../docs/docs/contrib"

[output.html]
additional-css = ["../extra_css/notices.css"]
theme = "navy"

[output.html.playground]
line-numbers = true
