[package]
name = "hartex_discord_commands"
version = "0.1.0"
edition = "2021"
description = """
Commands for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-http", "discord-model", "discord-util", "discord-util-builder", "logging-facilities"] }
hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_discord_commands_core = { path = "../hartex-discord-commands-core", features = ["derive"] }

hartex_localization_core = { path = "../../localization/hartex-localization-core" }
hartex_localization_macros = { path = "../../localization/hartex-localization-macros" }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }
hartex_kafka_utils = { path = "../../rust-utilities/hartex-kafka-utils" }

rdkafka = { version = "0.29.0", default-features = false, features = ["cmake-build", "external-lz4", "tokio"] }

[features]
