[package]
name = "hartex_discord_commands"
version = "0.5.1"
edition = "2021"
description = """
Commands for the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../../api-backend/hartex-backend-models" }
hartex_backend_models_v2 = { path = "../../api-backend/hartex-backend-models-v2" }

hartex_discord_cdn = { path = "../hartex-discord-cdn" }
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-http", "discord-mention", "discord-model", "discord-util", "discord-util-builder", "discord-util-snowflake"] }
hartex_discord_commands_core = { path = "../hartex-discord-commands-core", features = ["derive"] }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }
hartex_discord_entitycache_repositories = { path = "../hartex-discord-entitycache-repositories" }

hartex_localization_bindings = { path = "../../localization/hartex-localization-bindings" }
hartex_localization_core = { path = "../../localization/hartex-localization-core" }
hartex_localization_loader = { path = "../../localization/hartex-localization-loader" }
hartex_localization_macros = { path = "../../localization/hartex-localization-macros" }

hartex_log = { path = "../../rust-utilities/hartex-log" }
hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }

fluent-bundle = "0.15.2"
fluent-syntax = "0.11.0"
futures = "0.3.29"
hyper = { version = "0.14.27", features = ["client", "http2"] }
lazy_static = "1.4.0"
miette = "5.10.0"
serde_json = "1.0.108"

[features]
