[package]
name = "hartex_discord_commands"
version = "0.9.0"
edition = "2021"
description = """
Commands for the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.78.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../../api-backend/hartex-backend-models" }
hartex_backend_models_v2 = { path = "../../api-backend/hartex-backend-models-v2" }

hartex_discord_cdn = { path = "../hartex-discord-cdn" }
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-net", "discord-http", "discord-mention", "discord-model", "discord-util", "discord-util-builder", "discord-util-snowflake"] }
hartex_discord_commands_core = { path = "../hartex-discord-commands-core", features = ["derive"] }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }
hartex_discord_entitycache_repositories = { path = "../hartex-discord-entitycache-repositories" }

hartex_localization_core = { path = "../../localization/hartex-localization-core" }

hartex_log = { path = "../../rust-utilities/hartex-log" }
hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }

fluent-bundle = "0.15.2"
futures = "0.3.30"
http-body-util = "0.1.1"
hyper = { version = "1.2.0", features = ["client", "http2"] }
hyper-util = { version = "0.1.3", features = ["http2", "tokio"] }
miette = "7.2.0"
rand = "0.9.0-alpha.1"
serde_json = "1.0.114"

[features]
