[package]
name = "hartex_bors_github"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors Github things
"""
license = "AGPL-3.0-only"
rust-version = "1.71.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_core = { path = "../hartex-bors-core" }
hartex_bors_permissions = { path = "../hartex-bors-permissions" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

jsonwebtoken = "8.3.0"
octocrab = "0.22.0"
secrecy = "0.8.0"
serde = { version = "1.0.163", features = ["derive"] }

[features]
