[package]
name = "hartex_bors_github"
version = "0.5.1"
edition = "2021"
description = """
HarTex bors Github things
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_core = { path = "../hartex-bors-core" }
hartex_bors_database = { path = "../hartex-bors-database" }
hartex_bors_permissions = { path = "../hartex-bors-permissions" }

hartex_log = { path = "../../rust-utilities/hartex-log" }

futures = "0.3.29"
http = "0.2.11"
http-body = "0.4.5"
jsonwebtoken = "9.2.0"
miette = "5.10.0"
octocrab = "0.32.0"
secrecy = "0.8.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["sync"] }

[features]
