[package]
name = "hartex_backend_driver"
version = "0.1.0"
edition = "2021"
description = """
Backend server driver
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_ratelimiter = { path = "../hartex-backend-ratelimiter" }
hartex_backend_routes_v1 = { path = "../hartex-backend-routes-v1" }
hartex_backend_status_util = { path = "../hartex-backend-status-util" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

dotenvy = "0.15.7"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master" }
serde = "1.0.158"
serde_json = "1.0.94"

[features]
