[package]
name = "hartex_backend_driver"
version = "0.7.1"
edition = "2021"
description = """
Backend server driver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_routes = { path = "../hartex-backend-routes" }

hartex_errors = { path = "../../rust-utilities/hartex-errors" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

axum = "0.7.4"
bb8-postgres = "0.8.1"
dotenvy = "0.15.7"
hyper = { version = "1.1.0", features = ["http1", "server"] }
hyper-util = { version = "0.1.2", features = ["http1", "tokio"] }
miette = { version = "5.10.0", features = ["fancy"] }
serde = "1.0.196"
serde_json = "1.0.113"
tokio = { version = "1.35.1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["timeout", "trace"] }
tower-service = "0.3.2"
tracing = { version = "0.1.40", features = ["log-always"] }

[features]
