[package]
name = "hartex_backend_authenticator"
version = "0.1.0"
edition = "2021"
description = """
Backend server driver
"""
license = "AGPL-3.0-only"
rust-version = "1.70.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master" }

[features]
