[package]
name = "hartex_backend_layers"
version = "0.8.0"
edition = "2021"
description = """
Backend middleware
"""
license = "AGPL-3.0-or-later"
rust-version = "1.78.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
