[package]
name = "hartex_backend_layers"
version = "0.5.1"
edition = "2021"
description = """
Backend middleware
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "1.0.0"
http-body = "1.0.0"
log = "0.4.20"
pin-project-lite = "0.2.13"
tower-http = "0.5.0"
tower-service = "0.3.2"

[features]
