[package]
name = "hartex_backend_routes"
version = "0.12.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-or-later"
rust-version = "1.82.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../hartex-backend-models" }

hartex_database_queries = { path = "../../database/hartex-database-queries" }

hartex_log = { path = "../../rust-utilities/hartex-log" }

axum = { version = "0.7.5", features = ["json", "macros"] }
bb8-postgres = "0.8.1"
serde_json = "1.0.117"
time = "0.3.36"

[features]
