[package]
name = "hartex_discord_entitycache_entities"
version = "0.1.0"
edition = "2021"
description = """
The entity declarations of the repository cache middleware for HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.70.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core", features = ["derive"] }

[features]
