[package]
name = "hartex_discord_entitycache_entities"
version = "0.9.0"
edition = "2021"
description = """
The entity declarations of the repository cache middleware for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.78.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_database_queries = { path = "../../database-queries" }

hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core", features = ["derive"] }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }

tokio-postgres = "0.7.10"
twilight-model = { git = "https://github.com/TeamHarTex/twilight.git", branch = "next" }

[features]
