[package]
name = "hartex_backend_scylla_pool"
version = "0.1.0"
edition = "2021"
description = """
An implementation of a ScyllaDB pool.
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master" }
rocket_db_pools = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master" }
scylla = "0.7.0"

[features]
