[package]
name = "hartex_bitflags_utils"
version = "0.12.0"
edition = "2021"
description = """
Macro utilities
"""
license = "AGPL-3.0-or-later"
rust-version = "1.82.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.6.0"

[features]
