[package]
name = "hartex_discord_entitycache_core"
version = "0.7.1"
edition = "2021"
description = """
The core components of the repository cache middleware for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }
hartex_discord_entitycache_macros = { path = "../hartex-discord-entitycache-macros", optional = true }

bb8 = "0.8.1"
redis = { version = "0.24.0", features = ["tokio-comp"] }
tokio-postgres = "0.7.10"

[features]
derive = ["dep:hartex_discord_entitycache_macros"]
