[package]
name = "hartex_bors_permissions"
version = "0.2.0"
edition = "2021"
description = """
HarTex bors permission resolver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../../api-backend/hartex-backend-models" }
hartex_backend_models_v1 = { path = "../../api-backend/hartex-backend-models-v1" }

hartex_bors_core = { path = "../hartex-bors-core" }

hartex_log = { path = "../../rust-utilities/hartex-log" }

hyper = { version = "0.14.27", features = ["client", "http2"] }
miette = "5.10.0"
serde_json = "1.0.103"
tokio = { version = "1.29.1", features = ["sync"] }

[features]
