[package]
name = "hartex_bors_permissions"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors permission resolver
"""
license = "AGPL-3.0-only"
rust-version = "1.71.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../../api-backend/hartex-backend-models" }
hartex_backend_models_v1 = { path = "../../api-backend/hartex-backend-models-v1" }

hartex_bors_github = { path = "../hartex-bors-github" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

hyper = { version = "0.14.26", features = ["client", "http2"] }
serde_json = "1.0.96"
[features]
