[package]
name = "hartex_discord_configuration_runecli"
version = "0.7.1"
edition = "2021"
description = """
Rune CLI for HarTex's configuration API
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rune = { version = "0.13.1", features = ["cli"] }
