[package]
name = "hartex_bors_core"
version = "0.4.0"
edition = "2021"
description = """
HarTex bors database driver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.74.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "5.10.0"
octocrab = "0.31.0"
sea-orm = { version = "0.12.3", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1.32.0", features = ["sync"] }

[features]
