[package]
name = "hartex_bors_core"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors database driver
"""
license = "AGPL-3.0-only"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "5.9.0"
octocrab = { git = "https://github.com/TeamHarTex/octocrab.git" }
sea-orm = { version = "0.12.0-rc.4", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1.29.1", features = ["sync"] }

[features]
