[package]
name = "hartex_discord_commands_macros"
version = "0.7.1"
edition = "2021"
description = """
Macros for the command framework.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.75"
quote = "1.0.35"
syn = { version = "2.0.48", features = ["extra-traits", "full"] }

[features]

[lib]
name = "hartex_discord_commands_macros"
proc-macro = true
