[package]
name = "hartex_localization_bindings"
version = "0.5.1"
edition = "2021"
description = """
Localization bindings for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_localization_loader = { path = "../hartex-localization-loader" }

fluent-bundle = { git = "https://github.com/TeamHarTex/fluent-rs.git", branch = "main" }
fluent-syntax = { git = "https://github.com/TeamHarTex/fluent-rs.git", branch = "main" }
intl-memoizer = { git = "https://github.com/TeamHarTex/fluent-rs.git", branch = "main" }
miette = "5.10.0"
unic-langid = { version = "0.9.1", features = ["macros"] }

[lib]
name = "hartex_localization_bindings"
proc-macro = true

[features]
