[package]
name = "hartex_localization_bindings"
version = "0.8.0"
edition = "2021"
description = """
Localization bindings for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.78.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_localization_loader = { path = "../hartex-localization-loader" }

fluent-bundle = "0.15.2"
fluent-syntax = "0.11.0"
intl-memoizer = "0.5.1"
miette = "7.0.0"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.48"
unic-langid = { version = "0.9.4", features = ["macros"] }

[lib]
name = "hartex_localization_bindings"
proc-macro = true

[features]
