[package]
name = "hartex_discord_entitycache_repositories"
version = "0.6.0"
edition = "2021"
description = """
The repository declarations of the repository cache middleware for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_database_queries = { path = "../../database-queries" }

hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }
hartex_discord_entitycache_entities = { path = "../hartex-discord-entitycache-entities" }

redis = { version = "0.24.0", features = ["tokio-comp"] }
serde_scan = "0.4.1"
tokio-postgres = "0.7.10"

[features]
