[package]
name = "hartex_localization"
version = "0.1.0"
edition = "2021"
description = """
Localization infrastructure for HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }

fluent-bundle = "0.15.2"
intl-memoizer = "0.5.1"
unic-langid = { version = "0.9.1", features = ["macros"] }

[features]
