[package]
name = "hartex_bors_commands"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors database driver
"""
license = "AGPL-3.0-only"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_core = { path = "../hartex-bors-core" }
hartex_bors_database = { path = "../hartex-bors-database" }
hartex_bors_github = { path = "../hartex-bors-github" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

tokio = { version = "1.29.1", features = ["time"] }

[features]
