[package]
name = "hartex-macro-utils"
version = "0.1.0"
edition = "2021"
description = "Macro facilities"
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.43", features = ["full"]}

