[package]
name = "hartex_discord_cdn"
version = "0.5.1"
edition = "2021"
description = """
A wrapper for the Discord Content Delivery Network
"""
license = "AGPL-3.0-or-later"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }

[features]
