[package]
name = "hartex_discord_commands_core"
version = "0.11.0"
edition = "2021"
description = """
Core framework for commands.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.80.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }
hartex_discord_commands_macros = { path = "../hartex-discord-commands-macros", optional = true }

async-trait = "0.1.80"
miette = "7.2.0"

[features]
derive = ["dep:hartex_discord_commands_macros"]
