[package]
name = "hartex_discord_commands_core"
version = "0.2.0"
edition = "2021"
description = """
Core framework for commands.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }
hartex_discord_commands_macros = { path = "../hartex-discord-commands-macros", optional = true }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }

[features]
derive = ["dep:hartex_discord_commands_macros"]
