[package]
name = "hartex_backend_models"
version = "0.1.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-only"
rust-version = "1.70.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }

[features]
