[package]
name = "hartex_backend_models"
version = "0.6.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-or-later"
rust-version = "1.77.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
serde = { version = "1.0.193", features = ["derive"] }

[features]
