[package]
name = "hartex_bors_website"
version = "0.5.1"
edition = "2021"
description = """
HarTex bors permission resolver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_bors_core = { path = "../hartex-bors-core" }
hartex_bors_database = { path = "../hartex-bors-database" }

hartex_log = { path = "../../rust-utilities/hartex-log" }

async-lock = "3.1.2"
handlebars = { version = "5.0.0-beta.5", features = ["dir_source"] }
miette = { version = "5.10.0", features = ["fancy"] }
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master" }
serde = { version = "1.0.193", features = ["derive"] }

[features]
