[package]
name = "hartex_bors_website"
version = "0.1.0"
edition = "2021"
description = """
HarTex bors permission resolver
"""
license = "AGPL-3.0-only"
rust-version = "1.72.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
