name: Buildsystem

on: workflow_dispatch

jobs:
  BuildAndRelease:
    name: Build and Release Buildsystem
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Build buildsystem
        run: cd buildsystem && cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hartexbuild/target/release/hartexbuild
          tag_name: buildsystem-2023-03-08
          name: Buildsystem (8 March 2023)
