name: Lints

on:
  pull_request:
    branches:
      - nightly

env:
  CARGO_TERM_COLOR: always

jobs:
  ClippyDiscordFrontend:
    name: discord-frontend - Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/hartexbuild
      - name: Run Buildsystem
        run: chmod +x ./hartxexbuild && ./hartexbuild lint discord-frontend

  ClippyRustUtilities:
    name: rust-utilities - Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/hartexbuild
      - name: Run Buildsystem
        run: chmod +x ./hartxexbuild && ./hartexbuild lint rust-utilities

  ClippyLocalization:
    name: localization - Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/hartexbuild
      - name: Run Buildsystem
        run: chmod +x ./hartxexbuild && ./hartexbuild lint localization
