name: Lints

on:
  pull_request:
    branches:
      - nightly

env:
  CARGO_TERM_COLOR: always

jobs:
  ClippyDiscordFrontend:
    name: discord-frontend - Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh clippy discord-frontend

  RustfmtDiscordFrontend:
    name: discord-frontend - Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh formatck discord-frontend

  ClippyRustUtilities:
    name: rust-utilities - Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh clippy rust-utilities

  RustfmtRustUtilities:
    name: rust-utilities - Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh formatck rust-utilities

  ClippyLocalization:
    name: localization - Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh clippy localization

  RustfmtLocalization:
    name: localization - Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh formatck localization
