name: Lints

on:
  pull_request:
    branches:
      - nightly

env:
  CARGO_TERM_COLOR: always

jobs:
  ClippyDiscordFrontend:
    name: discord-frontend - Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/buildsystem
      - name: Run Buildsystem
        run: ./buildsystem clippy discord-frontend

  RustfmtDiscordFrontend:
    name: discord-frontend - Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/buildsystem
      - name: Run Buildsystem
        run: ./buildsystem formatck discord-frontend

  ClippyRustUtilities:
    name: rust-utilities - Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/buildsystem
      - name: Run Buildsystem
        run: ./buildsystem clippy rust-utilities

  RustfmtRustUtilities:
    name: rust-utilities - Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/buildsystem
      - name: Run Buildsystem
        run: ./buildsystem formatck rust-utilities

  ClippyLocalization:
    name: localization - Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/buildsystem
      - name: Run Buildsystem
        run: ./buildsystem clippy localization

  RustfmtLocalization:
    name: localization - Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-03-07/buildsystem
      - name: Run Buildsystem
        run: ./buildsystem formatck localization
