name: Tests

on:
  push:
    branches:
      - nightly
      - stable
      - automation/bors/approve
      - automation/bors/try

env:
  CARGO_TERM_COLOR: always

jobs:
  BuildAll:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Build
        run: python ./x.py build

  TestAll:
    name: Test
    needs:
      - BuildAll
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Build
        run: python ./x.py build -- discord-frontend
      - name: Run Tests
        run: python ./x.py test -- --ui --build-dir=build
