name: Tests

on:
  push:
    branches:
      - nightly
      - stable
      - automation/bors/approve
      - automation/bors/try

env:
  CARGO_TERM_COLOR: always

jobs:
  BuildApiBackend:
    name: api-backend - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild build api-backend

  BuildBors:
    name: bors - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild build bors

  BuildBuildsystem:
    name: buildsystem - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild build buildsystem

  BuildDiscordFrontend:
    name: discord-frontend - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild build discord-frontend

  TestDiscordFrontend:
    name: discord-frontend - Test
    needs:
      - BuildDiscordFrontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest
      - name: Install cargo-expand
        uses: dtolnay/install@cargo-expand
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild test discord-frontend

  BuildRustUtilities:
    name: rust-utilities - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild build rust-utilities

  BuildLocalizations:
    name: localization - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild build localization

  TestLocalizations:
    name: localization - Test
    needs:
      - BuildLocalizations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-11-04
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest
      - name: Install cargo-expand
        uses: dtolnay/install@cargo-expand
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild test localization
