name: Tests

on:
  push:
    branches:
      - nightly
      - stable
      - automation/bors/approve
      - automation/bors/try

env:
  CARGO_TERM_COLOR: always

jobs:
  BuildAll:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Build
        run: python ./x.py build

  TestDiscordFrontend:
    name: discord-frontend - Test
    needs:
      - BuildAll
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest
      - name: Install cargo-expand
        uses: dtolnay/install@cargo-expand
      - name: Download Buildsystem
        run: sudo wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2023-07-16/hartexbuild
      - name: Run Buildsystem
        run: sudo chmod +x ./hartexbuild && ./hartexbuild test discord-frontend
