name: Tests

on:
  push:
    branches:
      - nightly
      - stable
      - staging
      - trying

env:
  CARGO_TERM_COLOR: always

jobs:
  BuildDiscordFrontend:
    name: discord-frontend - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh build discord-frontend

  TestDiscordFrontend:
    name: discord-frontend - Test
    needs:
      - BuildDiscordFrontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-02-03
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Install cargo-expand
        uses: dtolnay/install@cargo-expand
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh test discord-frontend

  BuildRustUtilities:
    name: rust-utilities - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh build rust-utilities

  BuildLocalizations:
    name: localization - Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh build localization

  TestLocalizations:
    name: localization - Test
    needs:
      - BuildLocalizations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Install cargo-expand
        uses: dtolnay/install@cargo-expand
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: wget https://github.com/TeamHarTex/HarTex/releases/download/buildsystem-2022-12-07/buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh test localization
